### DISCUSSION TITLE
Strategy to Run TLS Demo on Proprietary KEM / DS PQCs

### DISCUSSION THREAD

**Discussion by quantropi-RYANTOTH** [open-quantum-safe/openssl#368] [General]
Hello,

This repo is very impressive -- thank you for your contributions. 

I have a DS and KEM PQC (not submitted to NIST) that I'd like to use in the TLS Demo for local testing. Is the best strategy for configuration adding the KEM / DS to the liboqs repo first, and then building liboqs inside of openssl OR is there a way to directly configure the two PQCs inside of openssl without changing liboqs? 

Please let me know if you have any suggestions. Thanks!

**Comment by christianpaquin** [comment]
The former is the best option: integrate the alg in OQS and then compile it into OpenSSL.

**Reply by baentsch** [reply]
+1. Additional benefit(s) of first integrating into `liboqs`: Automatic availability of this algorithm in OpenSSL3 (via [oqsprovider](https://github.com/open-quantum-safe/oqs-provider)), [oqs-openssh](https://github.com/open-quantum-safe/openssh), and the [profiling](https://openquantumsafe.org/benchmarking) framework.

**Comment by quantropi-RYANTOTH** [comment]
Hi again,

Over the past few days I've attempted to integrate two algorithms into OQS and then compile them into OpenSSL to conduct TLS benchmarking.

However, when I run the following command in OpenSSL to test a successful configuration it throws an error that it can't find the algorithm.

COMMAND:
`/home/ryan.toth/openssl/apps/openssl s_server -cert /home/ryan.toth/perf/test/server.crt -key /home/ryan.toth/perf/test/server.key -curves mppkl1 -www -tls1_3 -accept localhost:4433&` 

ERROR:
Warning: Algorithm name 'mppkl1' unknown. Check https://github.com/open-quantum-safe/openssl#supported-algorithms
Error with command: "-curves mppkl1"

I'm trying to grasp a deeper understanding on how OQS and OpenSSL communicate with each other, and I'm looking for some guidance as to why OpenSSL can't find the algorithm. I've outlined the configuration steps I've taken and some description about it below. 

Please let me know if you have any suggestions that might point me in the right direction and / or deeper my understanding on OQS and OpenSSL. Any help or comments are very much appreciated. Thank you!

Configuration Approach:
1. Integrate algorithm into OQS
- Created YML import file inside algorithm repo similar to [pqcrystals](https://github.com/pq-crystals/kyber)
- Added an entry to https://github.com/open-quantum-safe/liboqs/blob/main/scripts/copy_from_upstream/copy_from_upstream.yml 
- ran `python3 copy_from_upstream.py -k copy`
- build and install liboqs outlined [here](https://github.com/open-quantum-safe/openssl#building)

2. Compile OQS into OpenSSL
- used oqs-template to integrate my algorithms as outlined [here](https://github.com/open-quantum-safe/openssl/wiki/Contributing-Guide#adding-a-key-exchange-algorithm)

Note: the upstream script from liboqs didn't generate doc files for my algorithm (e.g. liboqs/docs/algorithms/kem) so I added them manually because `python3 oqs-template/generate.py` would fail otherwise

Note:  I didn't know what do put for the `nid` and `nid_hybrid` inside `oqs-template/generate.yml` so I used two locations that weren't already used in the table.

- Ran `./Configure no-shared linux-x86_64 -lm` and `make -j` and tested my configuration

**Reply by baentsch** [reply]
Before discussing oqs-OpenSSL integration, the first question is: Does your algorithm run successfully in the `liboqs` test suite? Does it show up when running `<liboqs>/build/tests/speed_kem --algs` (or ...speed_sig)? Does it pass the `liboqs` tests OK (running `...test_kem <alg_name>` (or test_sig)? Only if that works, the OpenSSL integration should be a topic. 

Also there you can check whether the baseline integration is OK by running `openssl speed test`: The output will show all integrated algorithms. Yours must be listed. If it isn't the integration didn't go OK. I assume no errors were output when you ran `generate.py`?

>  the upstream script from liboqs didn't generate doc files for my algorithm (e.g. liboqs/docs/algorithms/kem) so I added them manually because python3 oqs-template/generate.py would fail otherwise

This should not happen and might indicate an incorrect configuration. Can you post your algorithm's YML files, the `diff` of `copy_from_upstream.yml` and the error messages?

> I didn't know what do put for the nid and nid_hybrid inside oqs-template/generate.yml so I used two locations that weren't already used in the table.

That approach is OK, I'd recommend using `0x243` and `0x2F3` respectively. Also here, please post the `diff` to the current `generate.yml`.

**Reply by quantropi-RYANTOTH** [reply]
Hi baentsch, thanks for the quick response.

My algorithm seems to run successfully inside of `liboqs`
- I see my algorithm listed when running running `<liboqs>/build/tests/speed_kem --algs`
- Running `./test_kem MPPKL314` tells me that the shared secrets are equal

However, the doc files (yml and md files inside of `liboqs/docs/algorithms/kem`) are still not being generated when I run the upstream script. 

MY ALGORITHM YML FILE:

```
name: MPPKL314
type: kem
claimed-nist-level: 1
claimed-security: IND-CCA2
length-public-key: 328
length-ciphertext: 272
length-secret-key: 83
length-shared-secret: 32
nistkat-sha256:
principal-submitters:
  - Randy Kuang
auxiliary-submitters:
  - Maria Perepechaenko
  - Ryan Toth
implementations:
  - name: ref
    version: https://github.com/quantropi/mppk-kem-c/commit/870885059028c9f7f5f826e9aa81dfcef5a77987
    folder_name: crypto_kem/MPPK_L_supercop/ref
    compile_opts: -lgmp -lcrypto
    signature_keypair: quantropi_mppkl314_ref_keypair
    signature_enc: quantropi_mppkl314_ref_enc
    signature_dec: quantropi_mppkl314_ref_dec
    sources: kem.c bn_util.c api.h bn_util.h kem.h params.h
    supported_platforms:
      - architecture: x86_64
        operating_systems:
          - Linux
          - Darwin
        required_flags:
            - lgmp
            - lcrypto
```

DIFF of `copy_from_upstream.yml`: 

<img width="604" alt="Screen Shot 2022-05-07 at 10 03 38 AM" src="https://user-images.githubusercontent.com/97238253/167257674-c769a4c3-8de0-43d9-b18f-fed90cec18bf.png">

No errors were generated when running the upstream script.

Next, I added my algorithm to oqs-template `generate.yml` file. When I run `python3 oqs-template/generate.py` it throws an error that I'm missing `liboqs/docs/algorithms/kem/mppk.yml`

I can add this file manually to `liboqs` but it sounds like I shouldn't have to do that...

DIFF of `generate.yml` file inside `openssl`:

<img width="332" alt="Screen Shot 2022-05-07 at 10 17 14 AM" src="https://user-images.githubusercontent.com/97238253/167258160-302e54e4-cb8c-44e7-bd1f-acb99edea301.png">

Please let me know if you see any red flags in my configuration. Your help is fantastic -- I really appreciate it!!
